version: "3.3"

services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ 'CMD', 'rabbitmqctl', 'status' ]
      timeout: 10s
      interval: 30s
      retries: 3
    volumes:
      - ./rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbit/enabled_plugins:/etc/rabbitmq/enabled_plugins