name: 'NPM'
description: 'Installs NPM deps'

inputs:
  registry:
    description: 'NPM registry'
    default: 'https://registry.npmjs.org'
    required: false
  scope:
    description: 'NPM scope'
    required: false
  version:
    description: 'Node.JS version'
    required: false
    default: 18

runs:
  using: 'composite'
  steps:
    - name: Set Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.version }}
        cache: 'npm'
        registry-url: ${{ inputs.registry }}
        scope: ${{ inputs.scope }}

    - name: Install deps in quiet mode
      if: ${{ inputs.version == 18 }}
      shell: bash
      run: npm ci -q
      env:
        NODE_AUTH_TOKEN: ${{ env.NODE_AUTH_TOKEN }}

    - name: Install deps in quiet mode
      if: ${{ inputs.version == 14 }}
      shell: bash
      run: npm i -q
      env:
        NODE_AUTH_TOKEN: ${{ env.NODE_AUTH_TOKEN }}
