name: 'NPM'
description: 'Installs NPM deps'

inputs:
  registry:
    description: 'NPM registry'
    default: 'https://registry.npmjs.org'
    required: false
  scope:
    description: 'NPM scope'
    required: false
  version:
    description: 'Node.JS version'
    required: false
    default: "18"

runs:
  using: 'composite'
  steps:
    - name: Set Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.version }}
        cache: 'npm'
        registry-url: ${{ inputs.registry }}
        scope: ${{ inputs.scope }}

    - name: Update node-gyp
      shell: pwsh
      if: ${{ runner.os == 'windows' }}
      run : |
        # Find the location of node.exe
        $nodeExeLocation = Get-Command node | Select-Object -ExpandProperty Source
        # Extract the directory path from the node.exe location
        $nodeDir = [System.IO.Path]::GetDirectoryName($nodeExeLocation)
        Write-Output $nodeDir
        $nNodeDir = $nodeExeLocation | Split-Path
        Write-Output $nNodeDir
        # Install node-gyp
        npm i --prefix "$nodeDir\node_modules\npm\node_modules\@npmcli\run-script" node-gyp@9.4.0

    - name: Install deps in quiet mode
      shell: bash
      run: npm ci -q
      env:
        NODE_AUTH_TOKEN: ${{ env.NODE_AUTH_TOKEN }}
