name: 'NPM'
description: 'Installs NPM deps'

inputs:
  registry:
    description: 'NPM registry'
    default: 'https://registry.npmjs.org'
    required: false
  scope:
    description: 'NPM scope'
    required: false
  version:
    description: 'Node.JS version'
    required: false
    default: "20"
  cache:
    description: 'Cache'
    required: false
    default: "npm"


runs:
  using: 'composite'
  steps:
    - name: Set Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.version }}
        cache: ${{ inputs.cache }}
        registry-url: ${{ inputs.registry }}
        scope: ${{ inputs.scope }}

    # https://github.com/nodejs/node-gyp/blob/main/docs/Updating-npm-bundled-node-gyp.md#windows
    - name: Update node-gyp
      shell: pwsh
      if: ${{ runner.os == 'windows' }}
      run : |
        # Find the location of node.exe
        $nodeExeLocation = Get-Command node | Select-Object -ExpandProperty Source
        # Extract the directory path from the node.exe location
        $nodeDir = $nodeExeLocation | Split-Path
        # Install node-gyp
        npm i --prefix "$nodeDir\node_modules\npm\node_modules\@npmcli\run-script" node-gyp@9.4.0

    - name: Install deps in quiet mode
      shell: bash
      run: npm ci -q
      env:
        NODE_AUTH_TOKEN: ${{ env.NODE_AUTH_TOKEN }}
