[kdcdefaults]
    kdc_ports = 88,750

[realms]
    EXAMPLE.COM = {
        database_module = DB2
        acl_file = /etc/krb5kdc/kadm5.acl
        max_renewable_life = 7d
        supported_enctypes = aes256-cts-hmac-sha1-96:normal aes128-cts-hmac-sha1-96:normal
        default_principal_flags = +preauth
    }

[dbmodules]
    DB2 = {
        db_library = db2
    }
