name: CI / Automated testing

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci -q
      - run: npm run lint
      - run: npm run format
      - run: npm run test:unit
      - run: npm run test:e2e -- --testTimeout 4000
