name: CI / Automated testing

on:
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install deps
        uses: ./.github/workflows/composite/npm

      - run: npm run lint
      - run: npm run format
      - run: npm run test:unit
      - run: npm run test:e2e -- --testTimeout 4000
