name: Release Charts

on:
  push:
    branches:
      - IR-545/add_bright-cli_helm_chart

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Git
        run: |
          git config --global user.email "devops@brightsec.com"
          git config --global user.name "Bright Security"

      - name: Release packages main
        uses: helm/chart-releaser-action@v1.6.0
        with:
          mark_as_latest: false
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true
