name: Semantic release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GPR_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm ci -q
      - run: npm run build

      - run: npm run pack:win
      - run: npm run pack:linux
      - run: npm run pack:mac

      - name: Semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GPR_TOKEN }}
