name: Test checksum

on:
  pull_request:
    branches:
      - '**'

env:
  VERSION: ${{ github.event.release.tag_name }}
  TARGET_REF: ${{ github.event.release.target_commitish }}
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.TARGET_REF }}
          token: ${{ secrets.GPR_TOKEN }}

      - name: Install deps
        uses: ./.github/workflows/composite/npm

  build:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.TARGET_REF }}
          token: ${{ secrets.GPR_TOKEN }}

      - name: Install deps
        uses: ./.github/workflows/composite/npm

      - name: Set default distribution
        run: npm pkg set brightCli.distribution=package

      - name: Build package
        run: npm run build
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

      - name: Pack artifacts
        run: npm pack

      - uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./brightsec-cli-*
          tag: ${{ github.ref }}
          file_glob: true

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            dist
            Dockerfile
            package.json
            package-lock.json
            README.md
            LICENSE
            tools

  generate-binary:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            target: win
            node: 20
          - os: macos-13
            target: macos
            node: 20
          - os: ubuntu-20.04
            target: linux
            node: 20
            container:
              image: redhat/ubi8
              options: "--user root"
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.TARGET_REF }}
          token: ${{ secrets.GPR_TOKEN }}

      - uses: actions/download-artifact@v4
        with:
          name: build

      - name: Install dev-deps
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          dnf install -y dnf-utils \
          && dnf install -y python3 gcc gcc-c++ make \
          && rm -rf /var/cache/dnf

      - name: Install deps
        uses: ./.github/workflows/composite/npm
        with:
          version: ${{ matrix.node }}

      - name: Set distribution
        run: npx json -I -f package.json -e "this.brightCli.distribution='${{ matrix.target }}-executable'"

      - name: Build executable file
        run: npm run build:pkg -- -t node${{ matrix.node }}-${{ matrix.target }}-x64

      - name: Build MSI
        if: startsWith(matrix.os, 'win')
        run: .\tools\scripts\build-msi.ps1
        shell: pwsh

      - name: Calculate checksum
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "windows-2019" ]]; then
            certutil -hashfile ./bin/cli.exe SHA256 | grep -v "CertUtil" | tr -d " \t\n\r" > checksum.txt
            certutil -hashfile ./bin/bright-cli.msi SHA256 | grep -v "CertUtil" | tr -d " \t\n\r" >> checksum.txt
          else
            sha256sum ./bin/cli > checksum.txt
          fi

      - name: Print checksum
        run: cat checksum.txt
